name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: write-all

jobs:
  golint:
    name: Go Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

  build:
    name: Build and Test
    needs: golint
    
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        goVersion: ["1.18", "1.17", "1.16", "1.15", "1.14", "1.13"]
    
    steps:
    - name: Clone Repository 
      uses: actions/checkout@v3
      with:
          fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.goVersion }}

    - id: database
      uses: posteris/ci-database-starter@main

    - name: Test
      run: go test -v ./...
      
  sonar:
    runs-on: ubuntu-latest
    needs: build
    
    name: SonarCloud Scan
    
    steps:
      - id: database
        uses: posteris/ci-database-starter@main
      
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Test and coverage executions
        run: |
          mkdir -p bin
          go test -short -coverprofile=bin/cov.out ./...
      
      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  horusec:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0

      - name: Running Horusec Security
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest
          horusec start -p="./" -e="true"


  benchmark:
    name: Performance Regeression.
    runs-on: ubuntu-latest

    needs: [horusec, sonar]

    steps:
      - uses: actions/checkout@v2
      
      - id: database
        uses: posteris/ci-database-starter@main

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"
      
      - name: Run benchmark
        run:  go test -bench 'Benchmark' | tee output.txt
      
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'go'
          output-file-path: output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: '130%'